# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Endor Labs Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  ci-commons-demo-scan:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # -> Required by actions/checkout@v3 if checking out a private repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven
      - name: build with Maven
        run: mvn clean install -DskipTests

      - name: Endor Labs Scan Pull Request
        if: github.event_name == 'pull_request'
        uses: endorlabs/github-action@main
        with:
          namespace: "matt-learn"
          api_key: ${{ secrets.ENDOR_API_KEY_ID }}
          api_secret: ${{ secrets.ENDOR_API_SECRET_KEY }}
          enable_github_action_token: "false"
          scan_summary_output_type: "table"
          ci_run: "true"
      - name: Endor Labs Scan Push to main
        if: github.event_name == 'push'
        uses: endorlabs/github-action@main
        with:
          namespace: "matt-learn"
          api_key: ${{ secrets.ENDOR_API_KEY_ID }}
          api_secret: ${{ secrets.ENDOR_API_SECRET_KEY }}
          enable_github_action_token: "false"
          scan_summary_output_type: "table"
          ci_run: "false"
    
